[package]
name = "waboy"
version = "0.1.0"
authors = ["Yushi OMOTE <yushiomote@gmail.com>"]
edition = "2018"

[dependencies]
quicksilver = "0.3"
stdweb = "0.4"
rgy = { git = "https://github.com/YushiOMOTE/rgy.git" }
